name: flutter_application_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# uffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
# get:


  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  # google_sing_in: ^5.0.3

font_awesome_flutter: ^9.0.0
provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
get:
 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

 

  
